export const languages = [
	{ name: 'Afar' },
	{ name: 'Abkhazian' },
	{ name: 'Avestan' },
	{ name: 'Afrikaan' },
	{ name: 'Akan' },
	{ name: 'Amharic' },
	{ name: 'Aragonese' },
	{ name: 'Arabic' },
	{ name: 'Assamese' },
	{ name: 'Avaric' },
	{ name: 'Aymara' },
	{ name: 'Azerbaijani' },
	{ name: 'Bashkir' },
	{ name: 'Belarusian' },
	{ name: 'Bulgarian' },
	{ name: 'Bihari languages' },
	{ name: 'Bislama' },
	{ name: 'Bambara' },
	{ name: 'Bengali' },
	{ name: 'Tibetan' },
	{ name: 'Breton' },
	{ name: 'Bosnian' },
	{ name: 'Catalan; Valencian' },
	{ name: 'Chechen' },
	{ name: 'Chamorro' },
	{ name: 'Corsican' },
	{ name: 'Cree' },
	{ name: 'Czec' },
	{
		name: 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavoni',
	},
	{ name: 'Chuvash' },
	{ name: 'Welsh' },
	{ name: 'Danish' },
	{ name: 'German' },
	{ name: 'Divehi; Dhivehi; Maldivian' },
	{ name: 'Dzongkha' },
	{ name: 'Ewe' },
	{ name: 'Greek, Modern (1453-)' },
	{ name: 'English' },
	{ name: 'Esperanto' },
	{ name: 'Spanish; Castilian' },
	{ name: 'Estonian' },
	{ name: 'Basque' },
	{ name: 'Persian' },
	{ name: 'Fulah' },
	{ name: 'Finnish' },
	{ name: 'Fijian' },
	{ name: 'Faroese' },
	{ name: 'French' },
	{ name: 'Western Frisian' },
	{ name: 'Irish' },
	{ name: 'Gaelic; Scomttish Gaelic' },
	{ name: 'Galician' },
	{ name: 'Guarani' },
	{ name: 'Gujarati' },
	{ name: 'Manx' },
	{ name: 'Hausa' },
	{ name: 'Hebrew' },
	{ name: 'Hindi' },
	{ name: 'Hiri Motu' },
	{ name: 'Croatian' },
	{ name: 'Haitian; Haitian Creole' },
	{ name: 'Hungarian' },
	{ name: 'Armenian' },
	{ name: 'Herero' },
	{ name: 'Interlingua (International Auxiliary Language Association' },
	{ name: 'Indonesian' },
	{ name: 'Interlingue; Occidental' },
	{ name: 'Igbo' },
	{ name: 'Sichuan Yi; Nuosu' },
	{ name: 'Inupiaq' },
	{ name: 'Ido' },
	{ name: 'Icelandic' },
	{ name: 'Italian' },
	{ name: 'Inuktitut' },
	{ name: 'Japanese' },
	{ name: 'Javanese' },
	{ name: 'Georgian' },
	{ name: 'Kongo' },
	{ name: 'Kikuyu; Gikuyu' },
	{ name: 'Kuanyama; Kwanyama' },
	{ name: 'Kazakh' },
	{ name: 'Kalaallisut; Greenlandic' },
	{ name: 'Central Khmer' },
	{ name: 'Kannada' },
	{ name: 'Korean' },
	{ name: 'Kanuri' },
	{ name: 'Kashmiri' },
	{ name: 'Kurdish' },
	{ name: 'Komi' },
	{ name: 'Cornish' },
	{ name: 'Kirghiz; Kyrgyz' },
	{ name: 'Latin' },
	{ name: 'Luxembourgish; Letzeburgesch' },
	{ name: 'Ganda' },
	{ name: 'Limburgan; Limburger; Limburgish' },
	{ name: 'Lingala' },
	{ name: 'Lao' },
	{ name: 'Lithuanian' },
	{ name: 'Luba-Katanga' },
	{ name: 'Latvian' },
	{ name: 'Malagasy' },
	{ name: 'Marshallese' },
	{ name: 'Maori' },
	{ name: 'Macedonian' },
	{ name: 'Malayalam' },
	{ name: 'Mongolian' },
	{ name: 'Marathi' },
	{ name: 'Malay' },
	{ name: 'Maltese' },
	{ name: 'Burmese' },
	{ name: 'Nauru' },
	{ name: 'Bokmål, Norwegian; Norwegian Bokmå' },
	{ name: 'Ndebele, North; North Ndebele' },
	{ name: 'Nepali' },
	{ name: 'Ndonga' },
	{ name: 'Dutch; Flemish' },
	{ name: 'Norwegian Nynorsk; Nynorsk, Norwegian' },
	{ name: 'Norwegian' },
	{ name: 'Ndebele, South; South Ndebele' },
	{ name: 'Navajo; Navaho' },
	{ name: 'Chichewa; Chewa; Nyanja' },
	{ name: 'Occitan (post 1500)' },
	{ name: 'Ojibwa' },
	{ name: 'Oromo' },
	{ name: 'Oriya' },
	{ name: 'Ossetian; Ossetic' },
	{ name: 'Panjabi; Punjabi' },
	{ name: 'Pali' },
	{ name: 'Polish' },
	{ name: 'Pushto; Pashto' },
	{ name: 'Portuguese' },
	{ name: 'Quechua' },
	{ name: 'Romansh' },
	{ name: 'Rundi' },
	{ name: 'Romanian; Moldavian; Moldovan' },
	{ name: 'Russian' },
	{ name: 'Kinyarwanda' },
	{ name: 'Sanskrit' },
	{ name: 'Sardinian' },
	{ name: 'Sindhi' },
	{ name: 'Northern Sami' },
	{ name: 'Sango' },
	{ name: 'Sinhala; Sinhalese' },
	{ name: 'Slovak' },
	{ name: 'Slovenian' },
	{ name: 'Samoan' },
	{ name: 'Shona' },
	{ name: 'Somali' },
	{ name: 'Albanian' },
	{ name: 'Serbian' },
	{ name: 'Swati' },
	{ name: 'Sotho, Southern' },
	{ name: 'Sundanese' },
	{ name: 'Swedish' },
	{ name: 'Swahili' },
	{ name: 'Tamil' },
	{ name: 'Telugu' },
	{ name: 'Tajik' },
	{ name: 'Thai' },
	{ name: 'Tigrinya' },
	{ name: 'Turkmen' },
	{ name: 'Tagalog' },
	{ name: 'Tswana' },
	{ name: 'Tonga (Tonga Islands)' },
	{ name: 'Turkish' },
	{ name: 'Tsonga' },
	{ name: 'Tatar' },
	{ name: 'Twi' },
	{ name: 'Tahitian' },
	{ name: 'Uighur; Uyghur' },
	{ name: 'Ukrainian' },
	{ name: 'Urdu' },
	{ name: 'Uzbek' },
	{ name: 'Venda' },
	{ name: 'Vietnamese' },
	{ name: 'Volapük' },
	{ name: 'Walloon' },
	{ name: 'Wolof' },
	{ name: 'Xhosa' },
	{ name: 'Yiddish' },
	{ name: 'Yoruba' },
	{ name: 'Zhuang; Chuang' },
	{ name: 'Chinese' },
	{ name: 'Zulu' },
];
